language: node_js
node_js: 
  - node
branches:
 only:
  - master

script:
  - npm i
  - npm run test
cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"